// Program.cs

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllers();

// TODO: Register services with the dependency injection container.
// Instructions:
// 1. Place your cursor below this comment.
// 2. Start typing 'builder.Services.AddSingleton<'.
// 3. Use Copilot to suggest 'IItemService, ItemService' and 'ICategoryService, CategoryService'.
// 4. Accept the suggestions to complete the registrations.

// Code to be generated by Copilot:

// builder.Services.AddSingleton<IItemService, ItemService>();
// builder.Services.AddSingleton<ICategoryService, CategoryService>();

var app = builder.Build();

// Configure the HTTP request pipeline.

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
