// Models/Category.cs

namespace CopilotDemo.Models
{
    public class Category
    {
        // TODO: Add properties 'Id' and 'Name'.
        // Instructions:
        // 1. Place your cursor below this comment.
        // 2. Start typing 'public int Id { get; set; }'.
        // 3. Accept Copilot's suggestions for both properties.

        // Code to be generated by Copilot:

        // public int Id { get; set; }
        // public string Name { get; set; }
    }
}
