// Models/Item.cs

namespace CopilotDemo.Models
{
    public class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }

        // TODO: Add a property 'Description' of type string.
        // Instructions:
        // 1. Place your cursor below this comment.
        // 2. Start typing 'public string Description { get; set; }'.
        // 3. Copilot may suggest the property; accept it.

        // Code to be generated by Copilot:

        // public string Description { get; set; }
    }
}
